/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paintjava.gui;

/**
 *
 * @author vinicius
 */
public class MeuPaint extends javax.swing.JFrame {
    
    private int xPress;
    private int yPress;

    /**
     * Creates new form MeuPaint
     */
    public MeuPaint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoDesenho = new javax.swing.ButtonGroup();
        painelDesenho1 = new paintjava.gui.PainelDesenho();
        btnLinha = new javax.swing.JToggleButton();
        btnRetangulo = new javax.swing.JToggleButton();
        btnEclipse = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu paint");

        painelDesenho1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelDesenho1MouseDragged(evt);
            }
        });
        painelDesenho1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelDesenho1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelDesenho1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelDesenho1Layout = new javax.swing.GroupLayout(painelDesenho1);
        painelDesenho1.setLayout(painelDesenho1Layout);
        painelDesenho1Layout.setHorizontalGroup(
            painelDesenho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        painelDesenho1Layout.setVerticalGroup(
            painelDesenho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        btnGroupTipoDesenho.add(btnLinha);
        btnLinha.setSelected(true);
        btnLinha.setText("Linha");
        btnLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinhaActionPerformed(evt);
            }
        });

        btnGroupTipoDesenho.add(btnRetangulo);
        btnRetangulo.setText("Retangulo");
        btnRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetanguloActionPerformed(evt);
            }
        });

        btnGroupTipoDesenho.add(btnEclipse);
        btnEclipse.setText("Eclipse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelDesenho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRetangulo)
                .addGap(18, 18, 18)
                .addComponent(btnEclipse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLinha)
                    .addComponent(btnRetangulo)
                    .addComponent(btnEclipse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDesenho1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void painelDesenho1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenho1MousePressed
        
        xPress = evt.getX();
        yPress = evt.getY();
        

    }//GEN-LAST:event_painelDesenho1MousePressed

    private void painelDesenho1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenho1MouseReleased
        FormaGeometrica forma = null;
        
        if (btnLinha.isSelected()) {
            forma = new Linha();
            
        } else if (btnRetangulo.isSelected()) {
            
            forma = new Retangulo();
            
        }
        painelDesenho1.setFormaTemporaria(null);
        painelDesenho1.addFormas(forma);
        setCoord(forma, xPress, yPress, evt);
        
        painelDesenho1.repaint();
    }//GEN-LAST:event_painelDesenho1MouseReleased

    private void painelDesenho1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenho1MouseDragged
        FormaGeometrica formaTemp = null;
        if (btnLinha.isSelected()) {
            formaTemp = new Linha();
            
        } else if (btnRetangulo.isSelected()) {
            
            formaTemp = new Retangulo();
            
        }
        
        setCoord(formaTemp, xPress, yPress, evt);
        
        painelDesenho1.setFormaTemporaria(formaTemp);
        painelDesenho1.repaint();

    }//GEN-LAST:event_painelDesenho1MouseDragged

    private void btnLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLinhaActionPerformed

    private void btnRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetanguloActionPerformed
    
    public void setCoord(FormaGeometrica form, int xPress, int yPress, java.awt.event.MouseEvent evt) {
        
        form.setxInicial(xPress);
        form.setyInicial(yPress);
        form.setxFinal(evt.getX());
        form.setyFinal(evt.getY());
        
        painelDesenho1.setFormaTemporaria(form);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeuPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeuPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeuPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeuPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeuPaint().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEclipse;
    private javax.swing.ButtonGroup btnGroupTipoDesenho;
    private javax.swing.JToggleButton btnLinha;
    private javax.swing.JToggleButton btnRetangulo;
    private paintjava.gui.PainelDesenho painelDesenho1;
    // End of variables declaration//GEN-END:variables
}
